name: Java CI with Maven

on: [push, pull_request]  # This triggers the workflow on push or pull request events

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the type of runner to use

    steps:
    - uses: actions/checkout@v3  # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with: 
        java-version: '8'
        distribution: 'adopt'  # Using AdoptOpenJDK

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

    # Publish test results
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()  # This ensures that test results are published even if previous steps fail
      with:
        files: target/**/*.xml  # Specifies the location of the test result files

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: my-app-1.0
        path: target/*

    # Installe la commande docker sur l'agent
    - name: Install Docker
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true

    # Build l'image Docker
    - name: Docker build
      run: |
        docker build -t my-app-image:latest -f ./deploy.dockerfile .

